

void main() {

	sys.setcvar( "g_vehicleVelocity", "500" );
	sys.setcvar( "g_vehicleForce", "50000" );
//	sys.setcvar( "g_vehicleSuspensionUp", "32" );
//	sys.setcvar( "g_vehicleSuspensionDown", "20" );
	sys.setcvar( "g_vehicleSuspensionKCompress", "400" );
//	sys.setcvar( "g_vehicleSuspensionDamping", "400" );
//	sys.setcvar( "g_vehicleTireFriction", "0.8" );

	sys.setcvar( "g_showplayer", "0" );
	sys.setcvar( "g_showplayerShadow", "0" );
//	sys.setcvar( "pm_thirdPerson", "1" );
	sys.setcvar( "pm_thirdPersonRange", "200" );

	sys.setSpawnArg( "origin", "0 0 40" );
	sys.spawn( "env_simplebuggy" );
}
